### PR TITLE
internet_charge_type allow set to empty

### PR DESCRIPTION
**Pull request by likexian**
The `internet_charge_type` will set a default value when no specify, there is no way to leave it as empty.

This PR just not set the default value, server will fill the correct one.

### CODE REVIEW

**Comment by likexian** [comment]
I have test it, @nywilken , Would you please have a review?

**Review by nywilken — APPROVED** [review]
LGTM :+1: :+1:

**Comment by likexian** [comment]
@azr Would you please release this?

**Comment by azr** [comment]
All released ! 👍🏼

**Pull request merged**
